### ISSUE TITLE
@contentful\contentful-extension-scripts Missing from node_modules on Windows 10

### ISSUE THREAD

**Issue by JWambaugh** [contentful/create-contentful-extension#54]
After executing
```
cd contentful-deep-copy-extension
npm install && npm run login && npm run configure && npm run start
```
I get the following error:
```
> contentful-deep-copy-extension@0.1.0 start D:\devprojects\contentful-deep-copy-extension
> contentful-extension-scripts start

internal/modules/cjs/loader.js:969
    throw err;
    ^

Error: Cannot find module 'D:\devprojects\contentful-deep-copy-extension\node_modules\@contentful\contentful-extension-scripts\lib\index.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:966:17)
    at Function.Module._load (internal/modules/cjs/loader.js:859:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! contentful-deep-copy-extension@0.1.0 start: `contentful-extension-scripts start`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the contentful-deep-copy-extension@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```
A quick check of `node_modules` confirms there is no `@contentful\contentful-extension-scripts` path in `node_modules`.

![image](https://user-images.githubusercontent.com/23184/72181153-8c015100-339d-11ea-9dc8-08b469800763.png)

System: windows 10
Extension type: sidebar
Tried node versions 13.5.0 and 11.15.0

**Comment by JWambaugh** [comment]
I do not get this error on macOs. It only seems to affect windows systems

**Comment by jasonhill** [comment]
Any solution to this as I am seeing the same problem on a Windows 10 machine?

**Comment by SergeyRe** [comment]
npm install @contentful/contentful-extension-scripts

**Comment by Vluf** [comment]
Same with @contentful/eslint-config-extension

**Comment by Sporego** [comment]
Still missing `@contentful/eslint-config-extension` on windows 10
